// Bounded holding queue for frames captured while the broker socket is not OPEN.
//
// The relay's send path used to return silently whenever the socket was down, so the
// boot gap-fill EDIT_FEED that main posts right after its diff — and every live edit
// captured during a reconnect gap — was destroyed with nothing to show for it. This
// queue holds those frames until a socket is adopted, and when the cap is reached it
// drops the OLDEST frame and adds it to a tally the panel shows and the reconnect
// reports to the broker log (as PLUGIN_RELAY_STATS, right behind the handshake). A
// bounded queue can still lose an edit; what it cannot do is lose one quietly.
//
// Size is measured in serialized JSON characters, not bytes: the frame is already
// stringified at this point, and re-encoding every frame to UTF-8 purely to police a
// memory cap would cost a second full copy of the payload. For this traffic (JSON with
// mostly ASCII keys) the two are within a rounding error of each other.

/** Frame count / character cost of everything this session dropped. Session-cumulative. */
export interface PreOpenDrops {
  frames: number;
  chars: number;
}

export interface PreOpenBufferLimits {
  maxFrames: number;
  maxChars: number;
}

export const PRE_OPEN_MAX_FRAMES = 200;
export const PRE_OPEN_MAX_CHARS = 1_000_000;

/** main→broker capture traffic: the frames whose loss is silent data loss, because each
 *  one is a distinct edit the broker's feed will never see again. Everything else is
 *  excluded on purpose:
 *  - a reply, which is meaningless once the socket that asked for it died;
 *  - handshake/heartbeat control traffic, only valid on a live socket;
 *  - a click intent the user would rather re-issue than see replayed minutes later;
 *  - FILE_INFO, which is CURRENT STATE, not an event — main re-announces it on every
 *    selection change, so queueing it would let a user clicking around offline evict
 *    the very captures this buffer exists to protect, and the newest one rides the
 *    handshake anyway. */
const BUFFERED_EVENT_TYPES = new Set(['EDIT_FEED', 'DOC_CHANGE']);

/**
 * Serialize a capture frame for the buffer, stamping WHEN it was captured and marking it
 * a replay. Both facts are known here: a frame only ever enters this buffer because no
 * socket was OPEN, and the only way out of it is the reconnect flush.
 *
 * Without `capturedAt` the broker dates the frame at append time, which was true while an
 * unsendable frame was destroyed and became false the moment a whole outage got replayed
 * — a 40-minute gap would land in the feed as if it had all happened at the instant of
 * reconnect. `replayed` is the other half: the frames still legitimately carry
 * `source: 'live'` (they were live when captured), so the broker needs a separate,
 * explicit signal that this batch is history and must not wake a live waiter.
 */
export function stampCapturedFrame(
  msg: { type: string; data?: unknown }, capturedAt: number,
): string {
  const data = (typeof msg.data === 'object' && msg.data !== null ? msg.data : {}) as Record<string, unknown>;
  return JSON.stringify({ ...msg, data: { ...data, capturedAt, replayed: true } });
}

export function isBufferableFrame(msg: unknown): boolean {
  if (typeof msg !== 'object' || msg === null) return false;
  if ('id' in msg) return false; // a reply or a chunk of one
  const type = (msg as { type?: unknown }).type;
  return typeof type === 'string' && BUFFERED_EVENT_TYPES.has(type);
}

export interface PreOpenBuffer {
  /** Hold one serialized frame, evicting the oldest frames until the caps hold. */
  enqueue(json: string): void;
  /** Take everything held, in arrival order, and empty the queue. */
  drain(): string[];
  readonly size: number;
  readonly chars: number;
  /** A copy of the session-cumulative drop tally — never the live object. */
  readonly dropped: PreOpenDrops;
}

/**
 * Everything to write, in order, the moment a socket is adopted — split by who owns a
 * retry. `control` is regenerated by the NEXT connection from live state, so it is never
 * re-queued after a failed write; `captures` are the only frames whose loss would be
 * permanent, so those (and only those) go back in the buffer.
 */
export interface HandshakeBatch {
  /** PLUGIN_HELLO, then PLUGIN_RELAY_STATS when there is a loss to report. */
  control: string[];
  /** What the buffer held through the gap, in arrival order. */
  captures: string[];
}

/**
 * Build that batch. The order is the contract — the broker files an edit frame against a
 * REGISTERED plugin, so a capture that overtook its own PLUGIN_HELLO would arrive for a
 * plugin the broker has never heard of.
 *
 * The tally travels as its OWN event and only when something was actually lost. It is
 * NOT a hello field: a broker strips a fixed set of protocol keys out of the hello
 * payload and treats the rest as scene identity, so a growing tally riding the hello
 * would make every reconnect look like a scene change to a broker that predates it —
 * resetting the flapper streak its zombie watchdog counts on, precisely during the
 * connection trouble that produced the drops. An unknown event type costs that same
 * broker nothing. The tally is session-cumulative and therefore re-sent on every
 * reconnect; the broker logs the increment it has not already recorded.
 */
export function handshakeBatch(helloData: Record<string, unknown>, buffer: PreOpenBuffer): HandshakeBatch {
  const dropped = buffer.dropped;
  const control = [JSON.stringify({ type: 'PLUGIN_HELLO', data: helloData })];
  if (dropped.frames > 0) {
    control.push(JSON.stringify({ type: 'PLUGIN_RELAY_STATS', data: { preOpenDropped: dropped } }));
  }
  return { control, captures: buffer.drain() };
}

export function createPreOpenBuffer(limits: Partial<PreOpenBufferLimits> = {}): PreOpenBuffer {
  const maxFrames = limits.maxFrames ?? PRE_OPEN_MAX_FRAMES;
  const maxChars = limits.maxChars ?? PRE_OPEN_MAX_CHARS;
  const frames: string[] = [];
  let chars = 0;
  const dropped: PreOpenDrops = { frames: 0, chars: 0 };

  return {
    enqueue(json) {
      frames.push(json);
      chars += json.length;
      // A frame bigger than the whole cap evicts itself here rather than being held
      // as an exception: the cap is a memory bound, and the tally keeps it honest.
      while (frames.length > maxFrames || chars > maxChars) {
        const oldest = frames.shift();
        if (oldest === undefined) break;
        chars -= oldest.length;
        dropped.frames += 1;
        dropped.chars += oldest.length;
      }
    },
    drain() {
      const held = frames.slice();
      frames.length = 0;
      chars = 0;
      return held;
    },
    get size() { return frames.length; },
    get chars() { return chars; },
    get dropped() { return { ...dropped }; },
  };
}
